//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableToTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public string de_code { get; set; }
        public string de_name { get; set; }
        public string de_updepart { get; set; }
        public string de_function { get; set; }
        public Nullable<System.DateTime> de_registertime { get; set; }
        public string de_principal { get; set; }
        public string de_remarks { get; set; }
    }
}
