//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableToTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public string UserUsbhd { get; set; }
        public string UserIsUsbKey { get; set; }
        public string UserSpdeCode { get; set; }
        public Nullable<System.DateTime> UserCreateTime { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> StaffSex { get; set; }
        public string StaffDuty { get; set; }
        public string StaffIndentyCardID { get; set; }
        public Nullable<System.DateTime> StaffWorkTime { get; set; }
        public Nullable<System.DateTime> StaffBirthDay { get; set; }
        public Nullable<int> StaffAge { get; set; }
        public string StaffEducation { get; set; }
        public string StaffNation { get; set; }
        public string StaffPoliticalStatus { get; set; }
        public string StaffTitle { get; set; }
        public string StaffQualify { get; set; }
        public string StaffHighestEducation { get; set; }
        public string StaffGraduate { get; set; }
        public string StaffProfession { get; set; }
        public Nullable<System.DateTime> StaffGraducationTime { get; set; }
        public string StaffNativePlace { get; set; }
        public Nullable<int> StaffPageSize { get; set; }
        public string StaffIds { get; set; }
        public string StaffSocialInsuranceNO { get; set; }
        public string StaffAccumFundNO { get; set; }
        public string StaffFileNO { get; set; }
        public Nullable<int> StaffDepartmentID { get; set; }
        public string StaffDepartmentName { get; set; }
        public string StaffDegree { get; set; }
        public string StaffComment { get; set; }
        public Nullable<int> StaffPositionID { get; set; }
        public string StaffPositionName { get; set; }
        public Nullable<int> StaffStatus { get; set; }
        public string StaffBirthPlace { get; set; }
        public Nullable<System.DateTime> StaffComeUnitTime { get; set; }
        public Nullable<int> StaffEmployStatus { get; set; }
        public Nullable<int> StaffMarryStatus { get; set; }
        public string StaffFileAddr { get; set; }
        public string StaffAddr { get; set; }
        public string StaffHouseholdAddr { get; set; }
        public string StaffPhone { get; set; }
        public string StaffHousePhone { get; set; }
        public string StaffEmail { get; set; }
    }
}
