//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableToTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public string us_user { get; set; }
        public string us_password { get; set; }
        public string us_usbkeyhd { get; set; }
        public string us_isusbkey { get; set; }
        public string us_name { get; set; }
        public string de_code { get; set; }
        public string us_spdecode { get; set; }
        public string ro_code { get; set; }
        public string us_sex { get; set; }
        public string us_birthday { get; set; }
        public string po_code { get; set; }
        public string us_email { get; set; }
        public string us_phone { get; set; }
        public string us_mobile { get; set; }
        public string us_state { get; set; }
        public string us_createtime { get; set; }
        public string us_nationality { get; set; }
        public string us_nativeplace { get; set; }
        public string us_homeplace { get; set; }
        public string us_publicist { get; set; }
        public string us_marriage { get; set; }
        public string us_lastlydegree { get; set; }
        public string us_graduateschool { get; set; }
        public string us_graduatetime { get; set; }
        public string us_comeunittime { get; set; }
        public string us_retainingmode { get; set; }
        public string us_archives { get; set; }
        public string us_census { get; set; }
        public string us_identity { get; set; }
        public string us_speciality { get; set; }
        public string us_competence { get; set; }
        public string us_homeaddress { get; set; }
        public Nullable<int> us_pagesize { get; set; }
        public string no_ids { get; set; }
        public string us_remarks { get; set; }
    }
}
